### PR TITLE
Changes to Dex and Fixing Incorrect Dex Entries

### PR DESCRIPTION
**Pull request by JonnyACCI**
- Fixed incorrect entries for some pokemon that have other regional variants (the normal versions of the pokemon had the descriptions of their other regional variants in many cases, but I have made appropriate changes)
- Added descriptions for alolan and galarian variants
- Still Left: some descriptions for mega pokemon and special versions (like the cap pikas)

### CODE REVIEW

**Comment by oliver-ni** [comment]
Hi, thanks for your work. Can I ask how you made these changes (by hand?), and the source of the text?

**Comment by JonnyACCI** [comment]
Hey, no problem. I did them by hand. I used the website below for Pokedex entries. I noticed that the existing descriptions were using Pokemon Shield descriptions, so to stay consistent, I did the same.

[https://pokemondb.net/pokedex](url)

**Comment by FranieLUA** [comment]
nigga

**Comment by RedVertigoFox** [comment]
If you do not have a bug or suggestion, please go to general and then get the automod for being racist! have a nice day

**Comment by FranieLUA** [comment]
nigga

**Comment by FranieLUA** [comment]
nigga

**Comment by FranieLUA** [comment]
oliver is a femboy

**Comment by HatennaCollector** [comment]
Nice.

**Comment by FranieLUA** [comment]
cock n ball torture

**Comment by JonnyACCI** [comment]
Hey, will these new descriptions be added?

**Comment by oliver-ni** [comment]
Yes, sorry. Thanks for the PR.

**Pull request merged**
